management:
  security:
    enabled: true

security:
  user:
    name: admin
    password: admin
    role: USER,ADMIN
  basic:
    enabled: false

endpoints:
  sensitive: true

info:
  application:
    name: security-rest
    version: 1.0.0
